export const homeObj1 = {
    id: 'about',
    lightBg: true,
    lightText: false,
    darkText: true,
    ligthTextDest: false,
    topline1: 'Paprasčiau ir būti negali!',
    headline1: 'Rūšiuok atliekas',
    description1: 'Rink atliekas ir atsiusk mums jų nuotraukas. Už tai gausi atitinkamą taškų kiekį',
    topline2: 'Ir dar prizus gauni!',
    headline2: 'Rink taškus',
    description2: 'Galėsi stebėti savo progresą lyderių lentelėje, o surinktus taškus galėsi iškeisti į prizus',
    buttonLabel: 'Noriu pradėti!',
    imgStart: false,
    img1: require('../../images/picture1.svg').default,
    img2: require('../../images/picture2.svg').default,
    alt1: 'Recycle trash',
    alt2: 'Obtain rewards',
    dark: true,
    primary: true
}

export const homeObj2 = {
    id: 'goal',
    lightBg: false,
    lightText: false,
    darkText: true,
    ligthTextDest: false,
    topline1: 'Mūsų tikslas',
    headline1: 'Švari aplinka',
    description1: 'Tikimės patraukti kuo daugiau visuomenės prie rūšiavimo',
    topline2: 'Mūsų vizija',
    headline2: 'Švari Lietuva',
    description2: 'Norime, kad mūsų dėka Lietuva taptų mažiausiai šiukšlių aplinkoje turinti valstybe Europoje',
    buttonLabel: 'Noriu pradėti!',
    imgStart: false,
    img1: require('../../images/picture3.svg').default,
    img2: require('../../images/picture4.svg').default,
    alt1: 'Our goal',
    alt2: 'Our vision',
    dark: true,
    primary: true
}